# Generated by Django 4.1 on 2024-04-24 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_adding_pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, null=True)),
                ('breed', models.CharField(max_length=20, null=True)),
                ('stock', models.CharField(max_length=20, null=True)),
                ('age', models.CharField(max_length=20, null=True)),
                ('gender', models.CharField(max_length=20, null=True)),
                ('birthdate', models.CharField(max_length=20, null=True)),
                ('pic', models.ImageField(null=True, upload_to='media')),
                ('characteristics', models.CharField(max_length=20, null=True)),
                ('description', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
