# Generated by Django 4.1 on 2024-04-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0002_tbl_adding_pets'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_register_login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20, null=True)),
                ('lastname', models.CharField(max_length=20, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
