# Generated by Django 4.1 on 2024-05-06 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0003_tbl_register_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_Booking_Pets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.IntegerField(null=True)),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petsapp.tbl_adding_pets')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petsapp.tbl_register_login')),
            ],
        ),
    ]
