# Generated by Django 4.1 on 2024-05-06 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0004_tbl_booking_pets'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tbl_booking_pets',
            old_name='product',
            new_name='pet',
        ),
    ]
