# Generated by Django 4.1 on 2024-05-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0005_rename_product_tbl_booking_pets_pet'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_adding_products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('product_name', models.CharField(max_length=20, null=True)),
                ('price', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
