# Generated by Django 5.0.6 on 2024-05-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0006_tbl_adding_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_dr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctors_name', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(null=True, upload_to='media')),
                ('specialised', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
