# Generated by Django 5.0.1 on 2024-05-16 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0008_tbl_appoinment'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_pet_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('select_pet', models.CharField(max_length=20, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('age', models.IntegerField(null=True)),
                ('profession', models.IntegerField(null=True)),
                ('address', models.CharField(max_length=20, null=True)),
                ('landmark', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
