# Generated by Django 4.1.5 on 2024-05-23 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petsapp', '0009_tbl_pet_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_product_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=20, null=True)),
                ('landmark', models.CharField(max_length=20, null=True)),
                ('phone', models.IntegerField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petsapp.tbl_adding_products')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='petsapp.tbl_register_login')),
            ],
        ),
    ]
